import { AwsDbInstanceArgsIntterface } from '../interfaces';
import { AwsDbInstanceArgsEngine } from '.';

export class AwsDbInstanceArgs implements AwsDbInstanceArgsIntterface {
  allocated_storage: string;
  allow_major_version_upgrade?: string;
  apply_immediately?: string;
  auto_minor_version_upgrade?: string;
  availability_zone?: string;
  backup_retention_period?: string;
  backup_window?: string;
  character_set_name?: string;
  copy_tags_to_snapshot: string;
  db_subnet_group_name?: string;
  deletion_protection?: string;
  domain?: string;
  domain_iam_role_name: string;
  enabled_cloudwatch_logs_exports?: string;
  engine: AwsDbInstanceArgsEngine;
  engine_version?: string;
  final_snapshot_identifier?: string;
  iam_database_authentication_enabled?: string;
  identifier: string;
  identifier_prefix: string;
  instance_class: string;
  iops?: string;
  kms_key_id?: string;
  license_model: string;
  maintenance_window?: string;
  monitoring_interval?: string;
  monitoring_role_arn?: string;
  multi_az?: string;
  name?: string;
  option_group_name?: string;
  parameter_group_name?: string;
  password: string;
  port?: string;
  publicly_accessible?: string;
  replicate_source_db?: string;
  security_group_names: string;
  skip_final_snapshot?: string;
  snapshot_identifier?: string;
  storage_encrypted?: string;
  storage_type?: string;
  tags?: string;
  timezone?: string;
  username: string;
  vpc_security_group_ids?: string;
  s3_import?: string;
  create: string;
  update: string;
  delete: string;

}
